### ISSUE TITLE
Add Functionalities 

### ISSUE THREAD

**Issue by vinayaksinghmokhashi** [vinayaksinghmokhashi/Group8-Shop_Till_You_Want#2]
Please Update readme file with your project functionalities.

**Comment by Onkarbiyani** [comment]
Integrated Email Authentication with the main Project.

**Comment by Jaisinghal13** [comment]
As of now Firstly I worked on Login and register backend part.
• After that I worked on the products categories page that how we can see our products in different-different categories like mobile, fashion, and home-furnishing products.
• I also worked on the user name page to the navbar that how to use particular user names in the navbar.
• I worked on the orders page also in that orders can be seen by different-different users for their particular products ordered.
• Currently I am working on Admin Navbar.

**Comment by vinayaksinghmokhashi** [comment]
thanks for updating
